repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.13
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.11.2'  # Use the sha / tag you want to point at
  hooks:
    - id: mypy
      args: [--config-file, mypy.ini]
