flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: 80%
      - type: patch
        target: 80%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: pgscatalog.core  #fill in your own flag name
      paths: 
      - pgscatalog.core/
      carryforward: true
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 80%
    - name: pgscatalog.match 
      paths: 
      - pgscatalog.match/
      carryforward: true
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 80%
    - name: pgscatalog.calc 
      paths: 
      - pgscatalog.calc/
      carryforward: true
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 80%      
