import logging

from .lib import (
    Config,
    ScoreQueryResult,
    CatalogQuery,
    CatalogCategory,
    ScoringFiles,
    ScoringFile,
    NormalisedScoringFile,
    ScoreVariant,
    EffectType,
    GenomeBuild,
    TargetVariants,
    TargetVariant,
    BasePGSException,
    MatchError,
    DuplicateMatchError,
    MatchRateError,
    ZeroMatchesError,
    MatchValueError,
    CombineError,
    BuildError,
    ScoreFormatError,
    CatalogError,
    ScoreDownloadError,
    ScoreChecksumError,
    QueryError,
    InvalidAccessionError,
    SamplesheetError,
    GenomesNotFound,
    SamplesheetFormatError,
    RelabelArgs,
    relabel,
    relabel_write,
)

log_fmt = "%(name)s: %(asctime)s %(levelname)-8s %(message)s"
logging.basicConfig(format=log_fmt, datefmt="%Y-%m-%d %H:%M:%S")
logger = logging.getLogger(__name__)

__all__ = [
    "BasePGSException",
    "MatchError",
    "DuplicateMatchError",
    "MatchRateError",
    "ZeroMatchesError",
    "MatchValueError",
    "CombineError",
    "BuildError",
    "ScoreFormatError",
    "CatalogError",
    "ScoreDownloadError",
    "ScoreChecksumError",
    "QueryError",
    "InvalidAccessionError",
    "SamplesheetError",
    "GenomesNotFound",
    "SamplesheetFormatError",
    "ScoringFiles",
    "ScoringFile",
    "ScoreVariant",
    "Config",
    "GenomeBuild",
    "CatalogQuery",
    "ScoreQueryResult",
    "CatalogCategory",
    "TargetVariant",
    "TargetVariants",
    "NormalisedScoringFile",
    "EffectType",
    "RelabelArgs",
    "relabel",
    "relabel_write",
]
