name: Run CI on pgscatalog.match

on:
  push:
    paths:
      - 'pgscatalog.match/**.py'
  pull_request:
    paths:
      - 'pgscatalog.match/**.py'

jobs:
  ci-match:
    uses: ./.github/workflows/ci.yaml
    with:
      package-directory: "pgscatalog.match"