name: build and publish dev image

on:
  workflow_call:
  push:
    branches:
      - dev
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to EBI GitLab
        uses: docker/login-action@v3
        with:        
          registry: dockerhub.ebi.ac.uk
          username: gitlab-action
          password: ${{ secrets.GITLAB_TOKEN }}
          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: "pgscatalog.utils/docker/dev.Dockerfile"
          push: true
          tags: dockerhub.ebi.ac.uk/gdp-public/pygscatalog/pgscatalog-utils:dev
          platforms: linux/amd64,linux/arm64
